### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by gfregalado** [GMCCS/zambic-backend#12]
Hello

**Comment by gfregalado** [comment]
queres falar por aqui hj?

**Comment by gfregalado** [comment]
responde....

**Comment by gfregalado** [comment]
Gonçalo?

**Comment by GMCCS** [comment]
haha p crl
aceita o PR

**Comment by GMCCS** [comment]
kkkk

**Comment by gfregalado** [comment]
qual deles?

**Comment by gfregalado** [comment]
estavas cansado ontem?

**Comment by gfregalado** [comment]
ja acordastes?

**Comment by gfregalado** [comment]
vais almoçar onde?

**Comment by gfregalado** [comment]
Instala no telefone

**Comment by gfregalado** [comment]
Que fazem hj ao fim da tarde? Bebem uma chill?

**Comment by GMCCS** [comment]
- [ ] Hello

**Comment by GMCCS** [comment]
Pa n sei. Ha Jorge ben jor Cascais, deve tar de gala

**Comment by GMCCS** [comment]
Senão curtia miradouro c umas fresks?

**Comment by gfregalado** [comment]
Deve estar cheio de gente em Cascais

**Comment by gfregalado** [comment]
Responde no grupo agora

**Comment by GMCCS** [comment]
Oi

**Comment by gfregalado** [comment]
Foram babaji?

**Comment by GMCCS** [comment]
Tamos casa independente

**Comment by gfregalado** [comment]
Ainda bem que não fui

**Comment by gfregalado** [comment]
Babaji está fechado pq?

**Comment by GMCCS** [comment]
Ontem? Ou hj? N sei nada

**Comment by gfregalado** [comment]
estranhei

**Comment by GMCCS** [comment]
N

**Comment by gfregalado** [comment]
vai dormir

**Comment by gfregalado** [comment]
amanha terçou

**Comment by GMCCS** [comment]
Juízo

**Comment by gfregalado** [comment]
a que horas estas depachado hj?

**Comment by GMCCS** [comment]
N sei de estou despachado cedo

**Comment by GMCCS** [comment]
O melhor é irem que eu vou lá ter

**Comment by gfregalado** [comment]
estas com medo de ser despedido?
